CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -Wpedantic -Werror

SRCS = main.cpp permutation.cpp graphinitialisation.cpp colourlists.cpp conflictgraph.cpp greedyalgorithm.cpp

TARGET = myprog

all:
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET)

clean:
	rm -f $(TARGET)